name: start YCHackerNewsBot
#on: push
on:
  schedule:
    - cron:  '0 */6 * * *'   
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
    - name: install depends
      run: |
          sudo apt-get update
          sudo apt-get install -y npm
    - name: runs
      run: |
          npm install
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} npm start
